import { Link } from "react-router-dom";
import {
  ArrowRight,
  Mic,
  Activity,
  Target,
  Sparkles,
  Globe,
  ShieldCheck,
  CheckCircle2,
  XCircle,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const FEATURES = [
  {
    icon: Activity,
    title: "Real-time pitch curve",
    body:
      "Watch your voice contour overlay onto a native speaker's, frame by frame. See exactly where your tone diverges.",
  },
  {
    icon: Target,
    title: "Per-syllable diagnosis",
    body:
      "Three scores for every syllable: tone, initial, final. No more 'you got it right' lies — we tell you what went wrong.",
  },
  {
    icon: Sparkles,
    title: "Adaptive drilling",
    body:
      "We track your mistake patterns. The drill engine queues syllables you actually struggle with — not a generic course path.",
  },
  {
    icon: Globe,
    title: "Native-language tutor",
    body:
      "Gemini explains your mistakes in Uzbek, Russian, or English. No more guessing what 'aspirated retroflex' means.",
  },
];

const STATS = [
  { value: "21 × 38", label: "Initials × finals" },
  { value: "2,000+", label: "Practice items" },
  { value: "<300ms", label: "Pitch latency" },
  { value: "0", label: "Install steps" },
];

const COMPARISON = [
  ["Pitch curve overlay", { duolingo: false, hello: false, tp: true, us: true }],
  ["Per-phoneme scoring", { duolingo: false, hello: "partial", tp: true, us: true }],
  ["Adaptive (error-based)", { duolingo: false, hello: false, tp: "partial", us: true }],
  ["Uzbek / RU / EN tutor", { duolingo: false, hello: false, tp: false, us: true }],
  ["Web (no install)", { duolingo: false, hello: false, tp: true, us: true }],
  ["Free, no signup", { duolingo: false, hello: false, tp: true, us: true }],
] as const;

const FAQ = [
  {
    q: "Do I need to install anything?",
    a: "No. ShengAI runs entirely in your browser. Pitch analysis happens client-side, so your audio never leaves your device unless you opt into AI tutoring.",
  },
  {
    q: "How is this different from Duolingo or HelloChinese?",
    a: "Those apps grade your speech with a green tick or red cross. We show you the actual pitch curve, score each phoneme component separately, and adapt drills to your specific weaknesses.",
  },
  {
    q: "What languages can the tutor explain in?",
    a: "Uzbek, Russian, and English at launch. The explanation is generated by Google Gemini and tuned with a structured prompt that focuses on the linguistic cause, not generic encouragement.",
  },
  {
    q: "Is the pitch detection accurate?",
    a: "We use the YIN algorithm (Pitchy.js) for real-time F0 extraction and DTW alignment against canonical native contours. Accuracy depends on your mic — a headset gives the cleanest signal.",
  },
  {
    q: "Is my recording stored?",
    a: "Recordings stay in your browser. Only a short numerical summary (pitch scores) is sent to the Gemini API when you opt into AI tutoring, never the raw audio.",
  },
];

export function Landing() {
  return (
    <>
      <section className="relative overflow-hidden border-b border-border/60 bg-radial-fade">
        <div className="absolute inset-0 bg-grid opacity-50 [mask-image:radial-gradient(ellipse_at_center,black,transparent_70%)]" />
        <div className="container relative grid items-center gap-12 py-16 lg:grid-cols-2 lg:py-24">
          <div>
            <Badge variant="outline" className="mb-5 gap-1.5 border-primary/30 bg-primary/5 text-primary">
              <Sparkles className="h-3 w-3" />
              Build with AI EdTech Hackathon 2026
            </Badge>
            <h1 className="text-balance text-4xl font-bold leading-[1.05] tracking-tight sm:text-5xl lg:text-6xl">
              Master Mandarin pronunciation{" "}
              <span className="text-primary">your voice</span>, not your guesses.
            </h1>
            <p className="mt-5 max-w-xl text-balance text-lg text-muted-foreground">
              Real-time pitch overlay, per-syllable scoring, and an AI tutor that
              explains your mistakes in <strong>your own language</strong>.
              No install. No signup. Just press record.
            </p>
            <div className="mt-7 flex flex-wrap items-center gap-3">
              <Button asChild size="xl">
                <Link to="/test">
                  <Mic className="h-5 w-5" />
                  Take the free test
                  <ArrowRight className="h-4 w-4" />
                </Link>
              </Button>
              <Button asChild size="xl" variant="outline">
                <Link to="/pinyin">Browse pinyin chart</Link>
              </Button>
            </div>
            <div className="mt-8 flex flex-wrap items-center gap-x-6 gap-y-2 text-sm text-muted-foreground">
              <span className="inline-flex items-center gap-1.5">
                <ShieldCheck className="h-4 w-4 text-emerald-600" />
                Audio stays on-device
              </span>
              <span className="inline-flex items-center gap-1.5">
                <CheckCircle2 className="h-4 w-4 text-emerald-600" />
                Works offline (pitch only)
              </span>
              <span className="inline-flex items-center gap-1.5">
                <CheckCircle2 className="h-4 w-4 text-emerald-600" />
                Fully responsive
              </span>
            </div>
          </div>

          <HeroPreview />
        </div>
      </section>

      <section className="border-b border-border/60 bg-secondary/30">
        <div className="container grid grid-cols-2 gap-4 py-8 sm:grid-cols-4">
          {STATS.map((s) => (
            <div key={s.label}>
              <div className="text-2xl font-bold tracking-tight sm:text-3xl">{s.value}</div>
              <div className="text-sm text-muted-foreground">{s.label}</div>
            </div>
          ))}
        </div>
      </section>

      <section className="border-b border-border/60 py-16 lg:py-24">
        <div className="container">
          <div className="mx-auto max-w-2xl text-center">
            <Badge variant="outline" className="mb-3">How it works</Badge>
            <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">Three steps. Real feedback.</h2>
            <p className="mt-4 text-muted-foreground">
              Most apps give you a green tick. We give you the curve, the score, and the reason.
            </p>
          </div>

          <div className="mt-12 grid gap-6 md:grid-cols-3">
            {[
              { n: "01", title: "Read", body: "We show you a Chinese syllable or sentence with pinyin and tone marks." },
              { n: "02", title: "Record", body: "Press the mic and say it. Your voice never leaves the browser for analysis." },
              { n: "03", title: "Receive", body: "See your pitch overlay, three component scores, and an AI explanation in your language." },
            ].map((step) => (
              <div key={step.n} className="rounded-2xl border border-border/60 bg-card p-6">
                <div className="text-sm font-semibold tracking-widest text-primary">{step.n}</div>
                <h3 className="mt-3 text-xl font-semibold">{step.title}</h3>
                <p className="mt-2 text-muted-foreground">{step.body}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="border-b border-border/60 bg-secondary/30 py-16 lg:py-24">
        <div className="container">
          <div className="mx-auto max-w-2xl text-center">
            <Badge variant="outline" className="mb-3">Features</Badge>
            <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">What makes ShengAI different</h2>
          </div>
          <div className="mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
            {FEATURES.map(({ icon: Icon, title, body }) => (
              <div
                key={title}
                className="group rounded-2xl border border-border/60 bg-card p-6 transition-shadow hover:shadow-md"
              >
                <div className="grid h-11 w-11 place-items-center rounded-xl bg-primary/10 text-primary transition-transform group-hover:scale-110">
                  <Icon className="h-5 w-5" />
                </div>
                <h3 className="mt-4 text-lg font-semibold">{title}</h3>
                <p className="mt-2 text-sm text-muted-foreground leading-relaxed">{body}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="border-b border-border/60 py-16 lg:py-24">
        <div className="container">
          <div className="mx-auto max-w-2xl text-center">
            <Badge variant="outline" className="mb-3">vs. competitors</Badge>
            <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">Compare the field</h2>
            <p className="mt-4 text-muted-foreground">
              Mainstream apps pass you even when your pronunciation is wrong. Specialized tools fix tone but ignore everything else.
            </p>
          </div>
          <div className="mt-12 overflow-x-auto rounded-2xl border border-border/60">
            <table className="w-full min-w-[640px] text-sm">
              <thead className="bg-secondary/60 text-left">
                <tr>
                  <th className="px-4 py-3 font-semibold">Feature</th>
                  <th className="px-4 py-3 text-center font-semibold">Duolingo</th>
                  <th className="px-4 py-3 text-center font-semibold">HelloChinese</th>
                  <th className="px-4 py-3 text-center font-semibold">TonePerfect</th>
                  <th className="px-4 py-3 text-center font-semibold text-primary">ShengAI</th>
                </tr>
              </thead>
              <tbody>
                {COMPARISON.map(([label, vals], idx) => (
                  <tr key={label} className={idx % 2 === 0 ? "bg-background" : "bg-secondary/20"}>
                    <td className="px-4 py-3 font-medium">{label}</td>
                    <Cell value={vals.duolingo} />
                    <Cell value={vals.hello} />
                    <Cell value={vals.tp} />
                    <Cell value={vals.us} highlight />
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </section>

      <section className="border-b border-border/60 bg-secondary/30 py-16 lg:py-24">
        <div className="container">
          <div className="mx-auto max-w-2xl text-center">
            <Badge variant="outline" className="mb-3">Pricing</Badge>
            <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">Free during the hackathon</h2>
            <p className="mt-4 text-muted-foreground">
              All features are open for evaluation. No signup, no credit card.
            </p>
          </div>
          <div className="mx-auto mt-12 grid max-w-3xl gap-6 md:grid-cols-2">
            <div className="rounded-2xl border border-border/60 bg-card p-8">
              <div className="text-sm font-semibold uppercase tracking-wider text-muted-foreground">Free</div>
              <div className="mt-2 flex items-baseline gap-1">
                <span className="text-4xl font-bold">$0</span>
                <span className="text-sm text-muted-foreground">/ forever</span>
              </div>
              <ul className="mt-6 space-y-2 text-sm">
                {["Diagnostic test", "Pitch curve overlay", "Pinyin chart", "Daily workout", "Local progress"].map((f) => (
                  <li key={f} className="flex items-start gap-2">
                    <CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-emerald-600" />
                    {f}
                  </li>
                ))}
              </ul>
              <Button asChild className="mt-7 w-full">
                <Link to="/test">Start now</Link>
              </Button>
            </div>
            <div className="relative rounded-2xl border-2 border-primary/50 bg-card p-8 shadow-md">
              <Badge className="absolute -top-3 right-6">Future</Badge>
              <div className="text-sm font-semibold uppercase tracking-wider text-primary">Pro</div>
              <div className="mt-2 flex items-baseline gap-1">
                <span className="text-4xl font-bold">$9.99</span>
                <span className="text-sm text-muted-foreground">/ month</span>
              </div>
              <ul className="mt-6 space-y-2 text-sm">
                {[
                  "Unlimited AI tutor explanations",
                  "Adaptive SRS scheduling",
                  "Custom text upload",
                  "Cross-device sync",
                  "Advanced mistake analytics",
                ].map((f) => (
                  <li key={f} className="flex items-start gap-2">
                    <CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-primary" />
                    {f}
                  </li>
                ))}
              </ul>
              <Button asChild variant="outline" className="mt-7 w-full">
                <Link to="/test">Preview free →</Link>
              </Button>
            </div>
          </div>
        </div>
      </section>

      <section className="py-16 lg:py-24">
        <div className="container">
          <div className="mx-auto max-w-3xl">
            <div className="mb-10 text-center">
              <Badge variant="outline" className="mb-3">FAQ</Badge>
              <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">Common questions</h2>
            </div>
            <Accordion type="single" collapsible className="rounded-2xl border border-border/60 bg-card px-6">
              {FAQ.map((item, i) => (
                <AccordionItem key={i} value={`q-${i}`} className="last:border-b-0">
                  <AccordionTrigger>{item.q}</AccordionTrigger>
                  <AccordionContent>{item.a}</AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>
          </div>
        </div>
      </section>

      <section className="border-t border-border/60 bg-primary text-primary-foreground">
        <div className="container flex flex-col items-center gap-5 py-14 text-center">
          <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
            Stop guessing your tones.
          </h2>
          <p className="max-w-xl text-primary-foreground/85">
            Run the diagnostic. Two minutes. No signup. See where you actually stand.
          </p>
          <Button asChild size="xl" variant="secondary">
            <Link to="/test">
              <Mic className="h-5 w-5" />
              Take the free test
            </Link>
          </Button>
        </div>
      </section>
    </>
  );
}

function Cell({ value, highlight }: { value: boolean | "partial"; highlight?: boolean }) {
  return (
    <td className={`px-4 py-3 text-center ${highlight ? "bg-primary/5" : ""}`}>
      {value === true && <CheckCircle2 className="mx-auto h-5 w-5 text-emerald-600" />}
      {value === false && <XCircle className="mx-auto h-5 w-5 text-muted-foreground/50" />}
      {value === "partial" && (
        <span className="inline-block rounded-full bg-amber-500/15 px-2 py-0.5 text-xs font-medium text-amber-700">
          partial
        </span>
      )}
    </td>
  );
}

function HeroPreview() {
  // Decorative inline mock of the recording experience — not interactive.
  return (
    <div className="relative">
      <div className="absolute -inset-6 rounded-3xl bg-gradient-to-tr from-primary/20 via-amber-300/10 to-transparent blur-2xl" />
      <div className="relative rounded-3xl border border-border/60 bg-card p-6 shadow-xl">
        <div className="flex items-center justify-between text-sm">
          <span className="text-muted-foreground">Diagnostic · 3/5</span>
          <Badge variant="success">Tone 3 detected</Badge>
        </div>
        <div className="my-5 grid place-items-center py-4">
          <div className="font-chinese text-7xl">好</div>
          <div className="mt-2 text-lg text-muted-foreground">hǎo · "good"</div>
        </div>
        <div className="rounded-xl bg-secondary/40 p-3">
          <svg viewBox="0 0 300 90" className="h-24 w-full">
            <defs>
              <linearGradient id="heroRef" x1="0" y1="0" x2="0" y2="1">
                <stop offset="0%" stopColor="#10b981" stopOpacity={0.4} />
                <stop offset="100%" stopColor="#10b981" stopOpacity={0} />
              </linearGradient>
            </defs>
            <path d="M0,30 Q60,80 150,75 T300,25" fill="url(#heroRef)" stroke="#10b981" strokeWidth="2" />
            <path d="M0,40 Q70,75 155,72 T300,35" fill="none" stroke="hsl(var(--primary))" strokeWidth="2.5" />
          </svg>
        </div>
        <div className="mt-4 grid grid-cols-3 gap-2 text-center">
          {[
            { label: "Tone", value: 87 },
            { label: "Initial", value: 92 },
            { label: "Final", value: 78 },
          ].map((s) => (
            <div key={s.label} className="rounded-xl bg-secondary/50 p-3">
              <div className="text-2xl font-bold text-emerald-600">{s.value}</div>
              <div className="text-xs text-muted-foreground">{s.label}</div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
