"""
POST /api/explain

Turns the numeric scoring output into a short, native-language explanation
generated by Google Gemini. The frontend always provides a template-based
fallback, so this endpoint is allowed to fail loudly without breaking UX.

Request:
{
  "pinyin": "hǎo",
  "intendedTone": 3,
  "detectedTone": 2,
  "toneScore": 62,
  "initialScore": 78,
  "finalScore": 81,
  "lang": "uz"   // "uz" | "ru" | "en"
}

Response:
{ "text": "...", "source": "gemini" | "fallback" }

Why a structured prompt: we want the model to talk about the *linguistic
cause* (e.g. "your pitch rose instead of dipping") rather than generic
encouragement. We also constrain length to 2–3 sentences so the UI stays
tight.
"""
from __future__ import annotations

import os
from typing import Any

try:  # pragma: no cover — import-time soft dependency
    import google.generativeai as genai
except Exception:  # noqa: BLE001
    genai = None  # type: ignore[assignment]

from _utils import make_handler

GEMINI_MODEL = os.environ.get("GEMINI_MODEL", "gemini-2.0-flash")
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "").strip()

TONE_DESCRIPTION = {
    1: "high level (steady, high pitch)",
    2: "rising (mid to high)",
    3: "dipping (falls then rises)",
    4: "falling (sharp high-to-low)",
    5: "neutral (short, unstressed)",
}

LANG_LABEL = {
    "uz": "Uzbek (latin script)",
    "ru": "Russian",
    "en": "English",
}

SYSTEM_PROMPT = """You are ShengAI, an expert Mandarin pronunciation coach speaking to a learner.
Your job is to convert numeric pronunciation scores into actionable, friendly,
specific advice. Constraints:
  - Always answer in {language}, never in any other language.
  - 2–3 sentences total. No bullet points. No emoji.
  - Mention the *cause* of the issue (e.g. pitch shape, articulation place),
    not generic encouragement.
  - If tone is wrong, refer to what shape the user produced vs. the target.
  - End with one concrete thing to try next.
  - Never invent scores or claim certainty about the learner's accent.
"""


def _build_prompt(body: dict[str, Any]) -> tuple[str, str]:
    pinyin = body.get("pinyin")
    lang = body.get("lang", "en")
    language = LANG_LABEL.get(lang, LANG_LABEL["en"])
    system = SYSTEM_PROMPT.format(language=language)

    user = (
        f"Syllable: {pinyin}\n"
        f"Target tone: {body.get('intendedTone')} — {TONE_DESCRIPTION.get(int(body.get('intendedTone', 1)), '')}.\n"
        f"Detected tone: {body.get('detectedTone')} — "
        f"{TONE_DESCRIPTION.get(int(body.get('detectedTone', 1)), '')}.\n"
        f"Tone accuracy score: {body.get('toneScore')} / 100.\n"
        f"Initial (consonant) score: {body.get('initialScore')} / 100.\n"
        f"Final (vowel/ending) score: {body.get('finalScore')} / 100.\n\n"
        "Write the feedback now."
    )
    return system, user


def _gemini(system: str, user: str) -> str | None:
    if genai is None or not GEMINI_API_KEY:
        return None
    try:
        genai.configure(api_key=GEMINI_API_KEY)
        model = genai.GenerativeModel(
            model_name=GEMINI_MODEL,
            system_instruction=system,
            generation_config={
                "temperature": 0.5,
                "top_p": 0.9,
                "max_output_tokens": 220,
            },
        )
        resp = model.generate_content(user)
        text = (resp.text or "").strip()
        return text or None
    except Exception:  # noqa: BLE001
        return None


def _fallback(body: dict[str, Any]) -> str:
    """Defensive fallback in case both the LLM call and the frontend fail."""
    tone_ok = body.get("detectedTone") == body.get("intendedTone")
    base = (
        f"Your '{body.get('pinyin')}' came out as tone {body.get('detectedTone')}, "
        f"but the target is tone {body.get('intendedTone')}."
    )
    if tone_ok:
        base = f"Your tone for '{body.get('pinyin')}' is on the right shape — keep refining clarity."
    tip = "Match the green reference curve in shape, not just height."
    return f"{base} {tip}"


def post(body: dict[str, Any]) -> dict[str, Any]:
    if "pinyin" not in body:
        raise ValueError("pinyin is required")

    system, user = _build_prompt(body)
    text = _gemini(system, user)
    if text:
        return {"text": text, "source": "gemini"}

    return {"text": _fallback(body), "source": "fallback"}


handler = make_handler(post)
